name:                subnets-dsl
version:             0.1.0.0
github:              "krerkkiat/subnets-dsl"
license:             BSD3
author:              "Krerkkiat Chusap"
maintainer:          "contact@kchusap.com"
copyright:           "Copyright (c) 2021 Krerkkiat Chusap"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/krerkkiat/subnets-dsl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  subnets-dsl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subnets-dsl

tests:
  subnets-dsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subnets-dsl
    - hspec
    - hspec-contrib
